all:
  children:
    bbb_servers:
      hosts:
        bbb-server-01:
          ansible_host: server-ip
          ansible_user: ubuntu
          ansible_become: true
          ansible_become_method: sudo